### ISSUE TITLE
创建Application在与你的包名不同时不启正常启动

### ISSUE THREAD

**Issue by Kanjifeng** [han1396735592/spring-boot-starter-rxtx#1]

**Comment by han1396735592** [comment]
可以详细提供下截图信息吗

**Comment by SamkingChan** [comment]
同样遇到了这个问题，不知道为啥，哪里冲突了??
![image](https://user-images.githubusercontent.com/34914908/79324353-15e32c00-7f42-11ea-91aa-1592dd4fcf6c.png)

**Comment by han1396735592** [comment]
你少了一个dll 在这里 [dll地址](https://github.com/CMU-CREATE-Lab/commons-java/tree/master/java/lib/rxtx)
