### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by ruochen001** [han1396735592/spring-boot-starter-rxtx#5]
您好，感谢您开源的这个demo，对我帮助很大。但是项目在编译期间遇到点问题，想请求您的帮助。问题是这样的：在pom.xml文件中您引入了rxtx这个包，但是这个包的groupoId：cn.qqhxj.common，mvn仓库中搜索不到这个包，想知道这个包是您自己打包在您本地仓库里面吗，还是有其他jar开放平台可以获取的。希望能得到您的回复，感谢！

**Comment by han1396735592** [comment]
可以搜到的 https://developer.aliyun.com/mvn/search
```xml
<dependency>
    <groupId>cn.qqhxj.common</groupId>
     <artifactId>spring-boot-starter-rxtx</artifactId>
     <version>1.3.1-RELEASE</version>
</dependency>
```
![image](https://user-images.githubusercontent.com/29246573/133201367-34e72deb-2aec-440d-ae14-7c3cea10ea31.png)
