### ISSUE TITLE
你好，请问下，如果需要连接多个串口，读取多个串口的数据，这个适用吗？

### ISSUE THREAD

**Issue by guoWrok** [han1396735592/spring-boot-starter-rxtx#6]
你好，请问下，如果需要连接多个串口，读取多个串口的数据，这个适用吗？

**Comment by han1396735592** [comment]
不适用的

**Comment by han1396735592** [comment]
master 分支可以 需要自己下载代码打包

**Comment by guoWrok** [comment]
好的，谢谢

**Comment by guoWrok** [comment]
你好，再请教两个问题：
问题一：如果项目运行中，串口设备被拔线了，导致读取不到数据，这种情况该如何优化？
问题二：项目运行中，如果要修改串口号和波特率等串口信息，这些可以实时修改吗？修改完后，如何重新建立通讯呢？

**Comment by han1396735592** [comment]
这些暂不支持
